home/urls.py
from django.urls import path
from .views import *

urlpatterns =[
	
	#INICIO 

	path('inicio/',vista_inicio,name='vista_inicio'),
	path('',vista_login,name='vista_login'),
	path('logout/',vista_logout,name="vista_logout"),
#---------------------------------------------------------------------------------------------------------------------
	#BODREGA MATERIAL

	path('ver_detalle',detalle_ver,name='detalle_ver'),
	path('agrr_bodega_material',agr_bodega_materiall,name='agr_bodega_materiall'),
	path('editar_bodega_material/<int:id_bdm>/',editar_bodega_material,name="editar_bodega_material"),
	path('eliminar_bodega_material/<int:id_bdm>/',eliminarr_bodega_material,name="eliminarr_bodega_material"),
#-----------------------------------------------------------------------------------------------------------------
#urls de nombre_material
	path('agregar_nombre_material/',vista_agregar_nombre_material,name="vista_agregar_nombre_material"),
	path('editar_nombre_material/<int:id_nm>/',vista_editar_nombre_material,name="vista_editar_nombre_material"),
	path('eliminar_nombre_material/<int:id_nm>/',vista_eliminar_nombre_material,name="vista_eliminar_nombre_material"),
	path('lista_nombre_material/',vista_lista_nombre_material,name="vista_lista_nombre_material"),
#---------------------------------------------------------------------------------------------------------------
	# Detalle_Prestamo

	path('ListaD/',lista_DetallePrestamo,name='lista_DetallePrestamo'),
	path('verD/<int:id_Dprest>/',ver_DetallePrestamo,name='ver_DetallePrestamo'),
	path('eliminarD/<int:id_Dprest>/',elimnar_DetallePrestamo,name='elimnar_DetallePrestamo'),
#----------------------------------------------------------------------------------------------------------------
	#urls de marca
	path('lista_marca/',vista_lista_marca,name="vista_lista_marca"),
	path('agregar_marca/',vista_agregar_marca,name="vista_agregar_marca"),
	path('editar_marca/<int:id_marca>/',vista_editar_marca,name="vista_editar_marca"),
	path('eliminar_marca/<int:id_marca>/',vista_eliminar_marca,name="vista_eliminar_marca"),
#----------------------------------------------------------------------------------------------------------------
	#urls de materiales
	path('agregar_material/',vista_agregar_material,name="vista_agregar_material"),
	path('lista_material/',vista_lista_material,name="vista_lista_material"),
	path('editar_material/<int:id_material>/',vista_editar_material,name="vista_editar_material"),
	path('eliminar_material/<int:id_material>/',vista_eliminar_material,name="vista_eliminar_material"),
	path('ver_material/<int:id_material>/',vista_ver_material,name="vista_ver_material"),
#----------------------------------------------------------------------------------------------------------
#urls de devoluciones
	path('devolucion/<int:id_prest>/',devolucion_prestamo,name='devolucion_prestamo'),
#------------------------------------------------------------------------------------------------------------------	
	#urls de prestamo
	path('Lista/',lista_prestamo,name='lista_prestamo'),
	path('Agregar/',agregar_prestamo,name='agregar_prestamo'),
	path('editar/<int:id_prest>/',editar_prestamo,name='editar_prestamo'),
	path('elimnar/<int:id_prest>/',eliminar_prestamo,name='eliminar_prestamo'),
#------------------------------------------------------------------------------------------------------------------
	#urls de la tabla categoria
	path('categoria/',nombre_categoria,name="nombre_categoria"),
	path('editar_categoria/<int:id_cat>/',editarr_categoria,name='editarr_categoria'),
	path('agregar_categoria/',agr_categoria,name='agr_categoria'),
	path('eliminar_categoria/<int:id_cat>/',eliminarr_categoria,name='eliminarr_categoria'),

#--------------------------------------------------------------------------------------------------------------------
	# AQUI INICIAN LAS URLS DE BODEGA-----
	path('lista_bodega/',vista_lista_bodega, name='vista_lista_bodega'),
	path('ver_bodega/<int:id_bod>/',vista_ver_bodega,name='vista_ver_bodega'),
	path('agregar_bodega/',vista_agregar_bodega,name='vista_agregar_bodega'),
	path('editar_bodega/<int:id_bod>/',vista_editar_bodega, name= 'vista_editar_bodega'),
	path('eliminar_bodega/<int:id_bod>/',vista_eliminar_bodega, name= 'vista_eliminar_bodega'),

	# AQUI TERMINAN LAS URLS DE BODEGA-----

#----------------------------------------------------------------------------------------------------------------
	#urls de la tabla cuentadante
	path('vista_cuentadante',lista_cuentadante,name ='lista_cuentadante'),
	path('agr_cuentadante',agregar_cuentadante,name='agregar_cuentadante'),
	path('editar_cuentadante/<int:id_cue>/',editarr_cuentadante,name='editarr_cuentadante'),
	path('eliminar_cuentadante/<int:id_cue>/',eliminarr_cuentadante,name='eliminarr_cuentadante'),

#-----------------------------------------------------------------------------------------------------------------
	#urls de la tabla programa
	path('lista_programas/',vista_lista_programas, name = 'vista_lista_programas'),
	path('agregar_programas/',vista_agregar_programas, name = 'vista_agregar_programas'),
	path('editar_programas/<int:id_pro>/',vista_editar_programas, name = 'vista_editar_programas'),
	path('eliminar_programas<int:id_pro>/', vista_eliminar_programas, name='vista_eliminar_programas'),

#-----------------------------------------------------------------------------------------------------------------
	#urls de la tabla FICHA
	path('ver_ficha',detalle_ficha,name='detalle_ficha'),
	path('agregar_ficha',agr_ficha,name='agr_ficha'),
	path('editar_ficha/<int:id_fic>/',edit_ficha,name='edit_ficha'),
	path('eliminar_ficha/<int:id_fic>/',elim_ficha,name='elim_ficha'),

#-----------------------------------------------------------------------------------------------------------------
	#APRENDIZ
	path('lista_aprendiz/',vista_lista_aprendiz,name='vista_lista_aprendiz'),
	path('agregar_aprendiz/',vista_agregar_aprendiz,name='vista_agregar_aprendiz'),
	path('eliminar_aprendiz/<int:id_apr>/', vista_eliminar_aprendiz, name='vista_eliminar_aprendiz'),
	path('editar_aprendiz/<int:id_apr>/',vista_editar_aprendiz,name='vista_editar_aprendiz'),

#----------------------------------------------------------------------------------------------------------------
#urls de reportes
	path('reporte/',vista_reporte,name="vista_reporte"),
]

preIser/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

class Categoria (models.Model):
	nombre = models.CharField(max_length=100,unique=True)

	def __str__ (self):
		return self.nombre


class Bodega (models.Model):
	nombre = models.CharField(max_length=100,unique=True)
	foto = models.ImageField(upload_to='fotos',null = True, blank = True)

	def __str__ (self):
		return self.nombre


class Cuentadante (models.Model):
	nombre = models.CharField(max_length=100)
	identificacion = models.IntegerField(unique=True)

	def __str__ (self):
		return self.nombre
		

class Programa (models.Model):
	nombre = models.CharField(max_length=100,unique=True)

	def __str__ (self):
		return self.nombre


class Ficha (models.Model):
	numero_ficha = models.IntegerField(unique=True)
	fecha_inicio = models.DateField(auto_now=False, auto_now_add=False)
	fecha_finalizacion = models.DateField(auto_now=False, auto_now_add=False)
	estado= models.BooleanField(default=True)
	programa = models.ForeignKey(Programa, on_delete= models.CASCADE)

	def __str__ (self):
		return str(self.numero_ficha)

	#NO HAY CRUZ DE APRENDIZ

class Aprendiz (models.Model):
	nombre = models.CharField(max_length=100)
	identificacion = models.IntegerField(unique=True)
	tipo_documento = models.CharField(max_length=50)
	estado=models.BooleanField(default=True)
	ficha=models.ManyToManyField(Ficha,null=True,blank=True)

	def __str__ (self):
		return self.nombre
		
class Marca (models.Model):
	nombre = models.CharField(max_length=100,unique=True)

	def __str__ (self):
		return self.nombre

class Nombre_Material(models.Model):
	nombre = models.CharField(max_length=100,unique=True)

	def __str__(self):
		return self.nombre

class Material (models.Model):
	estado_choices=(
		('Disponible', 'Disponible'),
		('No Disponible', 'No Disponible'),
	)

	tipo_elemento = models.CharField(max_length=100)
	nombre = models.ForeignKey(Nombre_Material, on_delete=models.CASCADE)
	codigo_sena = models.CharField(max_length=100,unique=True,blank=True,null=True)
	numero_serie = models.CharField(max_length=100,unique=True,blank=True,null=True)
	cantidad = models.IntegerField(default=1,blank=True)
	estado = models.CharField(max_length=100,choices=estado_choices,default='Disponible')
	marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
	categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
	cuentadante = models.ForeignKey(Cuentadante, on_delete=models.CASCADE)
	ficha = models.ForeignKey(Ficha, on_delete=models.CASCADE)
	imagen=models.ImageField(upload_to='fotos',null = True, blank = True)

	def __str__ (self):
		return str(self.nombre)

class Bodega_Material(models.Model):
	material=models.ForeignKey(Material, on_delete=models.CASCADE)
	bodega=models.ForeignKey(Bodega, on_delete=models.CASCADE)
	fecha_ingresa=models.DateField(auto_now=False, auto_now_add=False)
	fecha_salida=models.DateField(auto_now=False, auto_now_add=False,null=True,blank=True)

	def __str__ (self):
		return str(self.material)

class Prestamo (models.Model):
	fecha_prestamo = models.DateField(auto_now=False, auto_now_add=False)
	estado = models.CharField(max_length=50)	
	aprendiz = models.ForeignKey(Aprendiz, on_delete= models.CASCADE)
	fecha_entrega=models.DateField(auto_now=False, auto_now_add=False)

	def __str__ (self):
		return self.estado

class Detalle_Prestamo(models.Model):
	material=models.ForeignKey(Material, on_delete=models.CASCADE)
	prestamo=models.ForeignKey(Prestamo, on_delete=models.CASCADE)
	cantidad = models.IntegerField()

	estado_elemento_prestamo=models.CharField(max_length=50,null=True,blank=True)
	descripcion=models.TextField(max_length=1000,null=True,blank=True)
	tipo_daño=models.CharField(max_length=6,null=True,blank=True)
	estado_devolucion=models.CharField(max_length=50,null=True,blank=True)
	fecha_devolucion=models.DateField(auto_now=False, auto_now_add=False,null=True,blank=True)

	def __str__ (self):
		return str(self.material)

home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class login_form (forms.Form):
	user = forms.CharField(widget=forms.TextInput(attrs={'class':'input100','name':'username',
														'placeholder':'Nombre de Usuario'}))
	password= forms.CharField(widget=forms.PasswordInput(render_value=False,attrs={'class':'input100',
													'name':'pass','placeholder':'Contraseña'}))
#formulario de la tabla nombre_material
class agregar_nombre_material_form(forms.ModelForm):
	class Meta:
		model = Nombre_Material
		fields = '__all__'
		widgets = {
			'nombre' : forms.TextInput(attrs={
			'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		}

#formulario de la tabla material
class agregar_material_form(forms.ModelForm):
	tipo_elemento = forms.ChoiceField(choices=([('Devolutivo','Devolutivo'), ('Consumible','Consumible') ]), initial='1', required = True,)
	class Meta:
		model = Material
		fields = '__all__'
#fromulario de la tabla material
class agregar_marca_form(forms.ModelForm):
	class Meta:
		model = Marca
		fields = '__all__'
		widgets = {
		'nombre' : forms.TextInput(attrs={
			'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		}
#formularios de la tabla prestamo
class agregar_prestamoF(forms.ModelForm):
	estado=forms.ChoiceField(choices=([('Activo','Activo'),('Terminado','Terminado')]))

	class Meta:
		model=Prestamo
		fields='__all__'
		widgets = {
		'fecha_prestamo':forms.TextInput(attrs={
			'class':'datepicker'
			}),
		'fecha_entrega' : forms.TextInput(attrs={
			'class':'datepicker'
			})
		}


class agregar_DPrestamoF(forms.ModelForm):
	material=forms.ModelChoiceField(queryset=Material.objects.filter(estado='Disponible'))
	class Meta:
		model=Detalle_Prestamo
		fields=['material','cantidad']

#-----------------------------------------------------------------------------------------------------

class dev_prestamoF(forms.ModelForm):
	fecha_prestamo=forms.DateField(disabled=True)
	estado=forms.ChoiceField(choices=([('Activo','Activo'),('Terminado','Terminado')]),disabled=True)
	aprendiz=forms.ModelChoiceField(Aprendiz.objects.all(),disabled=True)
	fecha_entrega=forms.DateField(disabled=True)

	class Meta:
		model=Prestamo
		fields='__all__'

class dev_DPrestamoF(forms.ModelForm):
	material=forms.ModelChoiceField(Material.objects.all(),disabled=True)
	estado_devolucion=forms.ChoiceField(choices=([('bueno','bueno'),('malo','malo')]))
	cantidad=forms.IntegerField()
	estado_elemento_prestamo=forms.ChoiceField(choices=([('En Prestamo','En Prestamo'),('Entregado','Entregado')]))
	tipo_daño=forms.ChoiceField(choices=([('Fisico','Fisico'),('Logico','Logico')]))



	class Meta:
		model=Detalle_Prestamo

		fields='__all__'
		widgets={
		'cantidad':forms.TextInput(attrs={
		'id':'contador'
		}),
		'fecha_devolucion' : forms.TextInput(attrs={
			'class':'datepicker'
		}),
		}
#-----------------------------------------------------------------------------------------
class det_prestamoF(forms.ModelForm):
	fecha_prestamo=forms.DateField(disabled=True)
	estado=forms.ChoiceField(choices=([('Activo','Activo'),('Terminado','Terminado')]),disabled=True)
	aprendiz=forms.ModelChoiceField(Aprendiz.objects.all(),disabled=True)
	fecha_entrega=forms.DateField(disabled=True)

	class Meta:
		model=Prestamo
		fields='__all__'

class det_DPrestamoF(forms.ModelForm):
	material=forms.ModelChoiceField(Material.objects.all(),disabled=True)
	estado_devolucion=forms.ChoiceField(choices=([('bueno','bueno'),('malo','malo')]))
	cantidad=forms.IntegerField(disabled=True)
	estado_elemento_prestamo=forms.ChoiceField(choices=([('En Prestamo','En Prestamo'),('Entregado','Entregado')]))
	tipo_daño=forms.ChoiceField(choices=([('Fisico','Fisico'),('Logico','Logico')]))



	class Meta:
		model=Detalle_Prestamo
		fields='__all__'

#formulario de la tabla categoria
class categoria_form(forms.ModelForm):
	class Meta:
		model = Categoria
		fields = '__all__'
		widgets = {
		'nombre' : forms.TextInput(attrs={
			'id':'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		}

#formulario de la tabla bodega
class agregar_bodega_form(forms.ModelForm):
	class Meta:
		model= Bodega
		fields= '__all__'
		widgets = {
			'nombre': forms.TextInput(attrs={
				'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
				}),
		}

#formulario de la tabla cuentadante
class cuentadante_form(forms.ModelForm):
	class Meta:
		model = Cuentadante
		fields = '__all__' 
		widgets = {
		'nombre' : forms.TextInput(attrs={
			'id':'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
			}),
		'identificacion' : forms.TextInput(attrs={
			'id' : 'identificacion','class':'form-control','placeholder':'Identificacion',
										'autofocus': 'autofocus','type':'number'
			}),
		}

#formulario de la tabla programa
class agregar_programas_form(forms.ModelForm):
	class Meta:
		model = Programa
		fields ='__all__'
		widgets = {
			'nombre' : forms.TextInput(attrs={
				'id' : 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
				}),
		}

class ficha_form(forms.ModelForm):
	class Meta:
		model = Ficha
		fields = '__all__'
		widgets= {
			'numero_ficha' : forms.TextInput(attrs={
				'id' : 'ficha','class':'form-control','placeholder':'Numero de Ficha',
										'autofocus': 'autofocus','type':'number'
				}),
			'fecha_inicio' : forms.TextInput(attrs={
				'id':'fecha_inicio','class':'datepicker form-control','placeholder':'Fecha de Inicio',
										'autofocus': 'autofocus'
				}),
			'fecha_finalizacion' : forms.TextInput(attrs={
				'id':'fecha_finalizacion','class':'datepicker form-control','placeholder':'Fecha de Finalizacion',
										'autofocus': 'autofocus'
				}),
		}


#formulario de la tabla bodega_material
class Bodega_Material_form(forms.ModelForm):
	class Meta:
		model = Bodega_Material
		fields = ['bodega','fecha_ingresa']
		widgets= {
			'fecha_ingresa' : forms.TextInput(attrs={
				'class' : 'datepicker'
				}),
			'fecha_salida' : forms.TextInput(attrs={
				'class' : 'datepicker'
				}),

		}

class agregar_aprendiz_form(forms.ModelForm):
	class Meta:
		model = Aprendiz
		fields = '__all__'
		widgets = {
			'nombre' : forms.TextInput(attrs={
			'id': 'nombre','class':'form-control','placeholder':'Nombre',
										'autofocus': 'autofocus'
				}),
			'identificacion' : forms.TextInput(attrs={
				'id' : 'identificacion','class':'form-control','placeholder':'Numero de identificacion',
										'autofocus': 'autofocus','type' : 'number'
				}),
			'tipo_documento' : forms.TextInput(attrs={
				'id' : 'tipo_documento','class':'form-control','placeholder':'Tipo de Documento',
										'autofocus': 'autofocus'
				}),
		}

templates/agregar_aprendiz.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
Agregar Aprendiz
{% endblock %}
{% block contenido %}
<div id="cajota">
  <div id="centrar">
	<h3>Agregar Aprendiz</h3>
  <br>
	<form action="" method="POST">
		{% csrf_token %}
		    <div class="form-group">
              <div >
                <div >
                	{{formulario.nombre.errors}}
                  <div class="form-label-group">
                    {{formulario.nombre}}
                    <label for="nombre">nombre</label>
                  </div>
                </div>
              </div>
           </div>

           <div class="form-group">
              <div >
                <div >
                	{{formulario.identificacion.errors}}
                  <div class="form-label-group">
                    {{formulario.identificacion}}
                    <label for="identificacion">Numero de Identificacion</label>
                  </div>
                </div>
              </div>
           </div>

            <div class="form-group">
              <div >
                <div >
                  {{formulario.tipo_documento.errors}}
                  <div class="form-label-group">
                    {{formulario.tipo_documento}}
                    <label for="tipo_documento">Tipo de Documento</label>
                  </div>
                </div>
              </div>
           </div>

            <div class="form-group">
              <div >
                <div >
                  {{formulario.estado.errors}}
                  <div class="form-label-group">
                    {{formulario.estado}}
                    <label for="{{formulario.estado.id_for_label}}">Estado</label>
                  </div>
                </div>
              </div>
           </div>

           <div class="form-group">
              <div >
                <div>
                  {{formulario.ficha.errors}}
                  <div class="form-label-group">
                    {{formulario.ficha|bootstrap}}
                  </div>
                </div>
              </div>
           </div>
        <button class="btn btn-success">Registrar Aprendiz</button>
	</form>		
		</div>
  </div>
{% endblock %}

templates/agregar_bodega_material.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
	Agregar bodega_material
{% endblock titulo %}
{% block contenido %}

<form action="" method="POST" enctype="multipart/form-data">

	{% csrf_token %}
	{{formulario|bootstrap}}
	<div class="col-md-3 text-center">
		<button class="btn btn-success">Registrar</button>
	</div>
</form>
<br>
	
{% endblock contenido %}

templates/agregar_prestamo.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
 Prestamo
{% endblock titulo %}
{% block contenido %}
<div id="cajota">
  <div id="centrar">
      <form action="" method="POST" >
          
        {% csrf_token %}
            <div >
                  <h3>Agregar Prestamo</h3>
                  <br>
                {{formulario|bootstrap}}
          
                {{ formset.management_form }}
            </div> 
            <div >
                    <h5 id="texto">No se permite repetir elementos</h5> 
                  {% for form in formset %}                
                        <div class="link-formset">
                          <fieldset id="f">
                            {{ form.id }}
                            <ul>
                                <div class="row">
                                  <div class="col-5">{{form.material|bootstrap}}</div>
                                  <div class="col-5">{{form.cantidad|bootstrap}}</div>
                                  <div class="col-2">{{form.DELETE|bootstrap}}</div>                              
                                </div>                
                            </ul>
                            </fieldset>
                        </div>
                    
                  {% endfor %}       
            </div>
                    
        <br>
        <input type="submit" value="AGREGAR PRESTAMO">
       

  </form>

  </div>
</div>

  







  
    <script>
    $('.link-formset').formset({
        addText: 'Agregar Elemento',
        deleteText: 'eliminar'
    });
</script>
  <script >
    $.datepicker.regional['es']={
      closeText:'Cerrar',
      prevText:'Anterior',
      nextText:'Siguiente',
      currenText:'Hoy',
      monthNames:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
      monthNamesShort:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
      dayNames:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
      dayNamesShort:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
      dayNamesMin:['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
      firstDay:1,
    };
    $.datepicker.setDefaults($.datepicker.regional['es']);
    $('.datepicker').datepicker();
  </script>
{% endblock contenido %}

templates/agregar_programa.html
{% extends "base.html" %}
{%block titulo%}
	agregar programa

{%endblock%}

{%block contenido%}
<div id="cajota">
  <div id="centrar">
    <h3>Agregar Programa</h3>
  <br>
	<form action="" method="POST">
		{% csrf_token %}
		    <div >
              <div >
                <div >
                	{{formulario.nombre.errors}}
                  <div class="form-label-group">
                    {{formulario.nombre}}
                    <label for="nombre">nombre</label>
                  </div>
                </div>
              </div>
           </div>
           <br>
        <button class="btn btn-success">Registrar Programa</button>
        
	</form>
  <br>
	<a href="{% url 'vista_lista_programas'%}" class="btn btn-primary">Regresar</a>
  
</div>
</div>
{%endblock%}

templates/categoria.html
{%extends "base.html"%}
{% load staticfiles %}
{% block titulo %}
Lista de Categorias

{%endblock %}

{%block contenido %}
<div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
              Lista de Categorias
            </div>
            <div class="card-body">
              <div class="btn_agregar">
                <a href="{% url 'agr_categoria'%}" class="btn btn-secondary" id="agregar">Agregar Categoria</a>  
              </div>
              <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>nombre</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>nombre</th>
                      <th></th>
                    </tr>
                  </tfoot>
                  <tbody>
                 	{% for p in lista %}
                 		<tr>
                 			<td>{{p.nombre}}</td>
                 			<td>
                        <a href="{% url 'editarr_categoria' id_cat=p.id %}" class="btn btn-sm">
                          <img src="{% static "imagenes/iconos/pencil-2x.png" %}">
                        </a>

                        <a href="{% url 'eliminarr_categoria' id_cat=p.id %}" class="btn btn-sm">
                          <img src="{% static "imagenes/iconos/trash-2x.png" %}">
                        </a>
                      </td>
                 		</tr>
                 		{% empty %}
          						<tr>
          							<td colspan="4">
          								No hay Datos Registrados
          							</td>
          						</tr>
                 	{% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
            <div class="card-footer small text-muted"></div>
    </div>
  
{%endblock%}

templates/vista_agregar_material.html
{% extends "base.html" %}
{% load bootstrap %}
{% block titulo %}
  Agregar Material
{% endblock titulo %}
{% block contenido %}
<div id="cajota">
  <div id="centrar">
    <h3>Agregar Material</h3>
  <br>
  <h5>
    {{ msj_bod }}
  </h5>
  <form action="" method="POST" name="f1" id="f1">
      {% csrf_token %}
      <div >
          {{formulario|bootstrap}}
          {{ bod.management_form }}
          {% for form in bod %}
          <div class="link-formset">
              {{ form.id }}
              <div class="row">
                <div class="col-6">{{form.bodega|bootstrap}}</div>
                <div class="col-6">{{form.fecha_ingresa|bootstrap}}</div>     
              </div>
          </div>
          {% endfor %}
          <button class="btn btn-success" type="submit">Guardar nuevo material</button>
      </div>
  </form>  <br>
  <a class="btn btn-secondary btn-sm" href="{% url 'vista_lista_material' %}">Regresar a la lista</a>
</div>
</div>


  <script type="text/javascript">
  	$(document).ready(function(){
			$('#id_cantidad').attr('disabled','disabled');
			$('#id_tipo_elemento').on('change',function(){
			var selectValor = '#'+$(this).val();
			if (selectValor=='#Devolutivo') {
				$('label[for="id_codigo_sena"]').show();
				$('#id_codigo_sena').show();
				$('#id_cantidad').attr('disabled','disabled');
			}
			else{
				$('#id_codigo_sena').hide();
				$('label[for="id_codigo_sena"]').hide();
				document.f1.id_cantidad.disabled=false;
			}
		});
	});
  </script>
  <script >
    $.datepicker.regional['es']={
      closeText:'Cerrar',
      prevText:'Anterior',
      nextText:'Siguiente',
      currenText:'Hoy',
      monthNames:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
      monthNamesShort:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'],
      dayNames:['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'],
      dayNamesShort:['Dom','Lun','Mar','Mié','Jue','Vie','Sáb'],
      dayNamesMin:['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
      firstDay:1,
    };
    $.datepicker.setDefaults($.datepicker.regional['es']);
    $('.datepicker').datepicker();
  </script>

{% endblock contenido %}